# Generated by Django 5.1.5 on 2025-05-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0007_alter_product_stock_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
