# Generated by Django 5.1.7 on 2025-03-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commissions',
            new_name='Commission',
        ),
    ]
